server:
  port: 8090 #\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u7AEF\u53E3\u53F7

eureka:
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 2000
  instance:
    hostname: localhost #\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u5B9E\u4F8B\u7684\u4E3B\u673A\u540D
  client:
    registerWithEureka: false #\u662F\u5426\u5411\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u6CE8\u518C\u81EA\u5DF1
    fetchRegistry: false #\u662F\u5426\u68C0\u7D22\u670D\u52A1
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka
  security:  #\u5982\u4E0B\u5B89\u5168\u914D\u7F6E\u662F\u8FDB\u5165eureka(\u8BBF\u95EElocalhost:8090)\u65F6,\u9700\u8981\u4E0B\u9762\u8D26\u53F7\u767B\u5F55\u9A8C\u8BC1
    basic:
      enable: true
    user:
      name: laohu
      password: 123456

logging:
  level:
    com.haoma.eureka: error

